"""create vote table

Revision ID: 1c7a8fc27490
Revises: d21d667e95d0
Create Date: 2026-01-14 18:51:34.261213

"""
# commands to use 
# alembic current     / for getting the current revison head
#alembic upgrade head      to upgrade the table or else and applu migration
# alembic revision --autogenerate -m "name"  to autogenrate the migration script from using models.py
#alembic downgrade      to rollback the chenges 

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c7a8fc27490'
down_revision: Union[str, Sequence[str], None] = 'd21d667e95d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_name'], ['users.user_name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_name')
    )
    op.drop_column('posts', 'age')
    op.create_unique_constraint(None, 'users', ['user_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('posts', sa.Column('age', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('likes')
    # ### end Alembic commands ###
