"""Update Vote Table

Revision ID: d65a53b7ae25
Revises: 1c7a8fc27490
Create Date: 2026-01-15 00:41:56.686059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65a53b7ae25'
down_revision: Union[str, Sequence[str], None] = '1c7a8fc27490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('direc', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('likes', 'direc')
    # ### end Alembic commands ###
